cd vsw-ortho-SP-BA/
bash vsw-ortho-SP-BA.sh
cd ../
cd vsw-ortho-SP-BB/
bash vsw-ortho-SP-BB.sh
cd ../
cd vsw-ortho-SP-BC/
bash vsw-ortho-SP-BC.sh
cd ../
cd vsw-ortho-SP-BD/
bash vsw-ortho-SP-BD.sh
cd ../
cd vsw-ortho-SP-BE/
bash vsw-ortho-SP-BE.sh
cd ../
cd vsw-ortho-SP-BF/
bash vsw-ortho-SP-BF.sh
cd ../
cd vsw-ortho-SP-BG/
bash vsw-ortho-SP-BG.sh
cd ../
cd vsw-ortho-SP-BH/
bash vsw-ortho-SP-BH.sh
cd ../
cd vsw-ortho-SP-BI/
bash vsw-ortho-SP-BI.sh
cd ../
cd vsw-ortho-SP-BJ/
bash vsw-ortho-SP-BJ.sh
cd ../
