cd vsw-ortho-SP-IA/
bash vsw-ortho-SP-IA.sh
cd ../
cd vsw-ortho-SP-IB/
bash vsw-ortho-SP-IB.sh
cd ../
cd vsw-ortho-SP-IC/
bash vsw-ortho-SP-IC.sh
cd ../
cd vsw-ortho-SP-ID/
bash vsw-ortho-SP-ID.sh
cd ../
cd vsw-ortho-SP-IE/
bash vsw-ortho-SP-IE.sh
cd ../
cd vsw-ortho-SP-IF/
bash vsw-ortho-SP-IF.sh
cd ../
cd vsw-ortho-SP-IG/
bash vsw-ortho-SP-IG.sh
cd ../
cd vsw-ortho-SP-IH/
bash vsw-ortho-SP-IH.sh
cd ../
cd vsw-ortho-SP-II/
bash vsw-ortho-SP-II.sh
cd ../
cd vsw-ortho-SP-IJ/
bash vsw-ortho-SP-IJ.sh
cd ../
