cd vsw-ortho-SP-DA/
bash vsw-ortho-SP-DA.sh
cd ../
cd vsw-ortho-SP-DB/
bash vsw-ortho-SP-DB.sh
cd ../
cd vsw-ortho-SP-DC/
bash vsw-ortho-SP-DC.sh
cd ../
cd vsw-ortho-SP-DD/
bash vsw-ortho-SP-DD.sh
cd ../
cd vsw-ortho-SP-DE/
bash vsw-ortho-SP-DE.sh
cd ../
cd vsw-ortho-SP-DF/
bash vsw-ortho-SP-DF.sh
cd ../
cd vsw-ortho-SP-DG/
bash vsw-ortho-SP-DG.sh
cd ../
cd vsw-ortho-SP-DH/
bash vsw-ortho-SP-DH.sh
cd ../
cd vsw-ortho-SP-DI/
bash vsw-ortho-SP-DI.sh
cd ../
cd vsw-ortho-SP-DJ/
bash vsw-ortho-SP-DJ.sh
cd ../
