cd vsw-ortho-SP-HA/
bash vsw-ortho-SP-HA.sh
cd ../
cd vsw-ortho-SP-HB/
bash vsw-ortho-SP-HB.sh
cd ../
cd vsw-ortho-SP-HC/
bash vsw-ortho-SP-HC.sh
cd ../
cd vsw-ortho-SP-HD/
bash vsw-ortho-SP-HD.sh
cd ../
cd vsw-ortho-SP-HE/
bash vsw-ortho-SP-HE.sh
cd ../
cd vsw-ortho-SP-HF/
bash vsw-ortho-SP-HF.sh
cd ../
cd vsw-ortho-SP-HG/
bash vsw-ortho-SP-HG.sh
cd ../
cd vsw-ortho-SP-HH/
bash vsw-ortho-SP-HH.sh
cd ../
cd vsw-ortho-SP-HI/
bash vsw-ortho-SP-HI.sh
cd ../
cd vsw-ortho-SP-HJ/
bash vsw-ortho-SP-HJ.sh
cd ../
