cd vsw-ortho-SP-GA/
bash vsw-ortho-SP-GA.sh
cd ../
cd vsw-ortho-SP-GB/
bash vsw-ortho-SP-GB.sh
cd ../
cd vsw-ortho-SP-GC/
bash vsw-ortho-SP-GC.sh
cd ../
cd vsw-ortho-SP-GD/
bash vsw-ortho-SP-GD.sh
cd ../
cd vsw-ortho-SP-GE/
bash vsw-ortho-SP-GE.sh
cd ../
cd vsw-ortho-SP-GF/
bash vsw-ortho-SP-GF.sh
cd ../
cd vsw-ortho-SP-GG/
bash vsw-ortho-SP-GG.sh
cd ../
cd vsw-ortho-SP-GH/
bash vsw-ortho-SP-GH.sh
cd ../
cd vsw-ortho-SP-GI/
bash vsw-ortho-SP-GI.sh
cd ../
cd vsw-ortho-SP-GJ/
bash vsw-ortho-SP-GJ.sh
cd ../
