cd vsw-ortho-SP-JA/
bash vsw-ortho-SP-JA.sh
cd ../
cd vsw-ortho-SP-JB/
bash vsw-ortho-SP-JB.sh
cd ../
cd vsw-ortho-SP-JC/
bash vsw-ortho-SP-JC.sh
cd ../
cd vsw-ortho-SP-JD/
bash vsw-ortho-SP-JD.sh
cd ../
cd vsw-ortho-SP-JE/
bash vsw-ortho-SP-JE.sh
cd ../
cd vsw-ortho-SP-JF/
bash vsw-ortho-SP-JF.sh
cd ../
cd vsw-ortho-SP-JG/
bash vsw-ortho-SP-JG.sh
cd ../
cd vsw-ortho-SP-JH/
bash vsw-ortho-SP-JH.sh
cd ../
cd vsw-ortho-SP-JI/
bash vsw-ortho-SP-JI.sh
cd ../
cd vsw-ortho-SP-JJ/
bash vsw-ortho-SP-JJ.sh
cd ../
