cd vsw-ortho-SP-EA/
bash vsw-ortho-SP-EA.sh
cd ../
cd vsw-ortho-SP-EB/
bash vsw-ortho-SP-EB.sh
cd ../
cd vsw-ortho-SP-EC/
bash vsw-ortho-SP-EC.sh
cd ../
cd vsw-ortho-SP-ED/
bash vsw-ortho-SP-ED.sh
cd ../
cd vsw-ortho-SP-EE/
bash vsw-ortho-SP-EE.sh
cd ../
cd vsw-ortho-SP-EF/
bash vsw-ortho-SP-EF.sh
cd ../
cd vsw-ortho-SP-EG/
bash vsw-ortho-SP-EG.sh
cd ../
cd vsw-ortho-SP-EH/
bash vsw-ortho-SP-EH.sh
cd ../
cd vsw-ortho-SP-EI/
bash vsw-ortho-SP-EI.sh
cd ../
cd vsw-ortho-SP-EJ/
bash vsw-ortho-SP-EJ.sh
cd ../
