cd vsw-ortho-SP-FA/
bash vsw-ortho-SP-FA.sh
cd ../
cd vsw-ortho-SP-FB/
bash vsw-ortho-SP-FB.sh
cd ../
cd vsw-ortho-SP-FC/
bash vsw-ortho-SP-FC.sh
cd ../
cd vsw-ortho-SP-FD/
bash vsw-ortho-SP-FD.sh
cd ../
cd vsw-ortho-SP-FE/
bash vsw-ortho-SP-FE.sh
cd ../
cd vsw-ortho-SP-FF/
bash vsw-ortho-SP-FF.sh
cd ../
cd vsw-ortho-SP-FG/
bash vsw-ortho-SP-FG.sh
cd ../
cd vsw-ortho-SP-FH/
bash vsw-ortho-SP-FH.sh
cd ../
cd vsw-ortho-SP-FI/
bash vsw-ortho-SP-FI.sh
cd ../
cd vsw-ortho-SP-FJ/
bash vsw-ortho-SP-FJ.sh
cd ../
