cd vsw-ortho-SP-CA/
bash vsw-ortho-SP-CA.sh
cd ../
cd vsw-ortho-SP-CB/
bash vsw-ortho-SP-CB.sh
cd ../
cd vsw-ortho-SP-CC/
bash vsw-ortho-SP-CC.sh
cd ../
cd vsw-ortho-SP-CD/
bash vsw-ortho-SP-CD.sh
cd ../
cd vsw-ortho-SP-CE/
bash vsw-ortho-SP-CE.sh
cd ../
cd vsw-ortho-SP-CF/
bash vsw-ortho-SP-CF.sh
cd ../
cd vsw-ortho-SP-CG/
bash vsw-ortho-SP-CG.sh
cd ../
cd vsw-ortho-SP-CH/
bash vsw-ortho-SP-CH.sh
cd ../
cd vsw-ortho-SP-CI/
bash vsw-ortho-SP-CI.sh
cd ../
cd vsw-ortho-SP-CJ/
bash vsw-ortho-SP-CJ.sh
cd ../
